version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Login_user
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    image: hoangvu42/web
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./front-end:/var/www/html
      - ./back-end:/var/www/html/back-end
    depends_on:
      - mysql

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - prometheus:/prometheus
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--web.enables-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'

  exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

volumes:
  mysql:
  grafana:
  prometheus:
